### ISSUE TITLE
MedPerf support for embedded MLCube config files

### ISSUE THREAD

**Issue by msheller** [mlcommons/medperf#109]
For the FeTS challenge, it would be ideal if we can support MLCube images with embedded parameters.yaml and mlcube.yaml files. This probably requires making these fields optional and having the client assume the files are embedded if they are not specified in the DB.

**Comment by aristizabal95** [comment]
This requires some features which I believe are still experimental from MLCube. @davidjurado can you confirm?
Additionally, we need to discuss how the server changes because of this.

Are we planning on supporting both current method as well as embbeded MLCube config?

**Comment by mzenk** [comment]
This is still an open issue, I think. @davidjurado  and I discussed that we could (for the FeTS challenge) also generate mlcube.yamls manually by inserting the correct image name into the template yaml file provided to the competitors. However, I don't know how this would affect the interaction with MedPerf, so I think we need to continue this discussion.

**Comment by hasan7n** [comment]
closing as outdated
