### ISSUE TITLE
Support "reject" responses

### ISSUE THREAD

**Issue by msheller** [mlcommons/medperf#13]
Currently, approvals are either "yes" or "cancel", meaning that we do not log to the server if approval was not given.

We should support the concept of "reject" so that the requesting party knows that a decision was made and can take next steps. To do this, we need to support this in the database as well as determine the right UI flow to make it clear to the user when they are "canceling" the decision (i.e. they don't yet know), or whether they are explicitly "rejecting" the request.

**Comment by aristizabal95** [comment]
This is now supported in #101
