### ISSUE TITLE
All tests should use string UIDs rather than integer UIDs

### ISSUE THREAD

**Issue by hasan7n** [mlcommons/medperf#139]
The following unit test:

 ```
@pytest.mark.parametrize("model_uid", rand_l(1, 500, 5))
def test_set_cube_uid_keeps_passed_uid_intact(
    mocker, default_setup, model_uid, comms, ui
):
```
Passes sometimes and fails sometimes.

It can be found in the script:
` medperf/cli/medperf/tests/commands/test_compatibility_test.py`

Most probably it fails for certain parameters that are randomly generated. To reproduce, replace ` rand_l(1, 500, 5)` in the parameterization with the list `[20,47,45]`. The following errors will be raised:

```
FAILED test_compatibility_test.py::test_set_cube_uid_keeps_passed_uid_intact[20] - AssertionError: assert 'test_1651680003' == 20
FAILED test_compatibility_test.py::test_set_cube_uid_keeps_passed_uid_intact[47] - AssertionError: assert 'test_1651680003' == 47
FAILED test_compatibility_test.py::test_set_cube_uid_keeps_passed_uid_intact[45] - AssertionError: assert 'test_1651680004' == 45
```

**Comment by hasan7n** [comment]
This bug is caused by passing `model_uid` as an integer rather than a string.

`model_uid` was passed to the `os.path.exists` function during the test. `os.path.exists` for python3.3+ treats integers as open files descriptors, so it returns `True` for some integers, causing the `model_uid` to change to a temporary UID that causes the assertion error.

All tests should be fixed to avoid any misleading future test failure.

**Comment by aristizabal95** [comment]
Awesome catch Hasan! What do you propose for this?
I'd say we need to make it explicit that the input to the function that is misbehaving should be a string. Maybe throw an error otherwise?
