### ISSUE TITLE
Documentation change request for example demo using CheXpert

### ISSUE THREAD

**Issue by dfeddema** [mlcommons/medperf#144]
Please update the MedPerf demo example documentation contained in the repo's README:
https://github.com/mlcommons/medperf#demo

Following the current documentation results in Medperf failure to preprocess the dataset.

Please add required step, "delete the "train.csv" file", to the README. 
Add this step after downloading the CheXpert dataset (e.g. " rm CheXpert-v1.0-small/train.csv"  ).
 
Otherwise the following line in the demo will fail:

"medperf dataset create -b 1 -d ~/CheXpert-v1.0-small -l ~/CheXpert-v1.0-small" 

unless you delete the "train.csv" file in 
**To Reproduce**
1. Install MedPerf server locally. Note make sure docker daemon is running on your local machine.
2. Run medperf demo in the repo's README: https://github.com/mlcommons/medperf#demo
3. See error "❌ There was an error while executing the cube. See logs at medperf.log for more information"

**Expected behavior**
MedPerf should preprocess the data and prompt the user for a name for the processed dataset.

**Additional context**
I ran this on MacOS Version 12.3.1

**Comment by aristizabal95** [comment]
@dfeddema thanks for reporting this. The README has been modified accordingly, and provides an explicit command for deleting the `train.csv` file. I'll close this for now, but feel free to reopen it if you feel the additions are not sufficient to run the test successfully.
