### ISSUE TITLE
Review the instructions for competitors to create MLCubes

### ISSUE THREAD

**Issue by aristizabal95** [mlcommons/medperf#160]

**Comment by mzenk** [comment]
I will create the instructions once we have a stable setup and the medperf team will review? Or are you already working on this?

**Comment by mzenk** [comment]
Oh, I forgot to provide the link to the PR with the instructions. You can find it [here](https://github.com/FETS-AI/Challenge/pull/171). The instructions can be found in the readme of Task 2.

**Comment by mzenk** [comment]
After incorporating feedback from @aristizabal95, I think this issue is done. Feel free to close it.

**Comment by aristizabal95** [comment]
Thanks for keeping us updated on this thread, and sorry for the silence! Closing this issue given your approval
