### ISSUE TITLE
Complete FeTS Task Schedule needs to be captured

### ISSUE THREAD

**Issue by aristizabal95** [mlcommons/medperf#161]

**Comment by mzenk** [comment]
My preliminary suggestion for schedule:
(need to discuss in the regular meeting if I missed tasks; also, I'm currently discussing with Upenn about extending the deadline by a few weeks, which would give us more time)

asap:

- [ ] Finish debugging compatibility test [DKFZ/medperf/mlcube]
- [ ] Run reference container to set timeout [DKFZ]
- [ ] Documentation for competitors (how to run medperf compatibility test) [DKFZ/medperf]

by June 27: 
- [ ] Documentation for data owners how to setup medperf and register their data [medperf]
- [ ] Final version of medperf server [medperf]

by July 4: 
- [ ] Find and prepare platform for storing singularity containers (submissions) [DKFZ]
- [ ] Upload submissions to platform and register them with medperf server [DKFZ]
- [ ] Final version of medperf client for federated evaluation [medperf]

by July 8:
- [ ] Install medperf at collaborating sites
- [ ] perform successful test-run in federation [medperf/DKFZ/UPenn]

**Comment by aristizabal95** [comment]
__Questions regarding Final version of medperf server:__
- Do we need an user authentication system for the Final version of medperf? We're looking into using Firebase and email/password authentication but we're not sure if this is necessary for the FeTS challenge.
- Will the FeTS team run their own instance of the medperf server? Or should we create an instance on our side specific to FeTS? (fets.medperf.org)

**Comment by mzenk** [comment]
Regardcing user authentication: Just for my understanding, the question is whether we need a mechanism that restricts access to the FeTS benchmark? The alternative would be that anyone who has the link or whatever can download, evaluate and upload results to the medperf folder? If my understanding is correct, I think there are two possible problems without authentication: 
- Anyone who has the link can download containers. This is not such a big deal, as the participants should make their code open source anyway afaik.
- Anyone could upload results. There is some (maybe small) risk of someone spamming the challenge with fake results. Also, without authentication, it could be hard to trace who submitted which results.
So in principle I'm in favor of authentication. Have you thought more on this?

Regarding medperf instance of FeTS team: I don't know of any infrastructure that's set up to host the server currently. What would we need to do for running our own instance? Spontaneously, I don't have a problem with you hosting the server, as long as we can access the results easily. I can check with my team if there are different opinions. Do you see any arguments for hosting it ourselves?

**Comment by aristizabal95** [comment]
Thanks for your answer

Currently, the medperf server has the basic Django authentication system implemented. Additionally, we don't have a system for people to create their own accounts directly. This means that people need to contact us (the medperf server owner to be more precise) so we can create their account. 

Access to basically any asset or action on the server is restricted to those who have an account. Results are only visible to the benchmark owner (and admin) at the moment.

The way I understand things will work with the FeTS challenge (and please correct me if I'm wrong) is that participants won't have an account. They will only interact with medperf for running tests. Once submissions are over, the FeTS team will submit the mlcubes under their own account, and the benchmark will be executed on data participants under their own account. Am I correct here?

As for some reasons we thought running your own instance might be preferable is if there are privacy concerns with the current implementation (say concerns that a bug or for some other reason private data is leaked). In such cases, the server can be managed by the benchmark owner, and restricted to only be accessible to those that need to (ip whitelisting for example). If these concers are not shared by the team, then we can absolutely run the experiment with the current server (https://medperf.org)

**Comment by mzenk** [comment]
Ok, your understanding of how the FeTS challenge is supposed to play out is correct. I guess we could just make accounts for all data participants, then?

About the server: Mayber we can talk about this in the next meeting; I'm not sure how large the risk is.

**Comment by aristizabal95** [comment]
Closing as discussion is way overdue. We've already covered this topics in different places/meetings.
