### ISSUE TITLE
User management & auth solution

### ISSUE THREAD

**Issue by aristizabal95** [mlcommons/medperf#165]
Determine and implement the tools for users to manage their accounts.

Given that FeTS participants are most probably going to use terminal-only instances, we don't need to think of an auth solution that uses a web UI.

**Comment by aristizabal95** [comment]
Related to #2 and #35

**Comment by aristizabal95** [comment]
Currently users need to get in contact with us to create an account. They can change their password through the cli, and if required, we can reset their password. This is the solution we arrived at for the FeTS Challenge

**Comment by hasan7n** [comment]
fixed
