### ISSUE TITLE
Unclear error message when using local model mlcube with -m

### ISSUE THREAD

**Issue by mzenk** [mlcommons/medperf#166]
Not really a bug but rather bad documentation/error feedback. When using the -m argument for specifying a path to a local model cube that should be used for inference, the directory containing the mlcube.yaml file (and workspace) is expected, I think. One could also have the idea to pass the path to the mlcube.yaml (mlcube allows both, I think), but this does not work currently (on branch `cli-assoc-comp-test`). 

To reproduce this: I ran `medperf --platform=singularity test -b 1 -m path/to/local/cube/mlcube.yaml`.
I get the following error message, which does not help to identify the problem:
```
❌ Couldn't find credentials file. Did you run 'medperf login' before?. See logs at /home/m167k/.medperf/logs/medperf.log for more information
```

**Expected behavior**
If a path to mlcube.yaml is provided, one option would be to use the parent directory as the mlcube folder. Alternatively, check if the path of -m is a directory and otherwise adapt the error message to show something like "you need to provide the path to the mlcube folder". Also update the documentation accordingly.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: None (offline compatibility testing)
 - Version: medperf commit 2164c081430c97fb7e3ef2f09c631cfab355007f

**Comment by mzenk** [comment]
@aristizabal95 github currently doesn't let me add this to the FeTS project.

**Comment by aristizabal95** [comment]
@mzenk good catch! I just added this to the FeTS project. I believe I sent you an invite a few days ago to be part of the medperf dev team, so you can do those modifications directly. I'm happy to help here either way if you can't add them

**Comment by aristizabal95** [comment]
Commit [a38fa27](https://github.com/mlcommons/medperf/pull/101/commits/a38fa27a4bcabdb73a7cba1ee996dc3faf9954e4) for #101 should fix this issue. Let me know if that's the case

**Comment by aristizabal95** [comment]
Hey @mzenk was this issue fixed? Just want to see if I can start closing some pending issues

**Comment by mzenk** [comment]
I made a quick test and now the correct cube is executed even if the path to the mlcube.yaml is provided (not the direcory). So seems to work (from my limited testing).

**Comment by aristizabal95** [comment]
Closing as it seems to be resolved now. Feel free to reopen it with a comment if that isn't the case
