### ISSUE TITLE
MedPerf Client needs to ensure TLS unless an "allow-insecure-comms" flag is set.

### ISSUE THREAD

**Issue by msheller** [mlcommons/medperf#169]
Right now, the medperf client doesn't require use of TLS, which is risky because the username/password could be sent over the network if the user doesn't pay attention to the URL they set the server to.

We need the client to ensure TLS is in use (verify=True only applies when TLS is used. It doesn't force it's use).

For now, to support development, we can add a --allow-insecure-comms flag to medperf CLI to skip the TLS check (which doesn't have anything to do with verify=True in requests).

In the meantime, we need to scope using self-signed certs for local development deployments. Django appears to support using self-signed certs, so if we can simply pass that same cert to the client, it can set that cert path in the verify field, e.g. "verify=../server/self_signed_cert.crt". That would ensure the client only connects to a server whose cert matches the self-signed cert on the local filesystem.

**Comment by aristizabal95** [comment]
Looking at this guide
https://ubuntu.com/server/docs/security-certificates
I found that one could add a certificate to the default list of certificates by adding it to `/etc/ssl/certs` and `/etc/ssl/private`. I think following this structure is really appealing, as the user doesn't have to care in most scenarios about the certificate. If running things locally, the certificate will be automatically added to those paths and the platform will trust the self-signed certificate. If then they use a remote deployment with a CA-signed certificate then nothing changes from the user's perspective.

Would it be possible for the server to create this certificates and automatically move them to the specified folders? That would be amazing

**Comment by aristizabal95** [comment]
This was fixed with PR #189
