### ISSUE TITLE
What are the MedPerf/MLCube requirements for singularity submissions?

### ISSUE THREAD

**Issue by mzenk** [mlcommons/medperf#183]
When thinking about where to store the final singularity submissions for the FeTS challenge, I was wondering if there are any requirements from the MedPerf/MLCube side on how the containers can be downloaded. So far, we experimented with docker images stored in docker hub or another registry, but this will not be possible for the singularity images used in the federated evaluation. 
My questions are: 
@aristizabal95 Is there a separate step in MedPerf that pulls a submission before running the benchmark or is MedPerf restricted to the MLCube functionality for pulling cubes? (In the latter case, I guess we would have to add the download commands to a script that is independent of medperf.)
@davidjurado Is it correct that the singularity runner of MLCube currently only supports running a .sif file that is stored locally?

**Comment by aristizabal95** [comment]
@mzenk There is no separate step in MedPerf for that. Pulling MLCube images is done through mlcube itself. I will talk to Micah about this, but I believe it would be preferable to maintain it that way, so as to keep separation of concerns. I think the script solution is a good workaround

**Comment by mzenk** [comment]
Ok, as a side note: one thing to also take into account is that when using inference timeout with the current implementation, the download time will be counted towards inference time, right? While this is usually only a small part, it could be non-negligible if there are few test cases and we wouldn't want to give algorithms less time that take longer to pull for some reason (may even be due to connection issues). I'll keep this issue open until we've found a solution for FeTS.

**Comment by hasan7n** [comment]
outdated
