### ISSUE TITLE
UI Mockups for current list of pages

### ISSUE THREAD

**Issue by aristizabal95** [mlcommons/medperf#188]
It would be great to implement/design some mockups to have a brief idea of how we want the website to look like. The pages we currently have in mind are:

Home Screen (each bullet is a page linked off of the parent)
- Benchmarks list
  - Benchmark “homepage” - basic information
    - Request/Confirm association (in cases where compatibility test is required, redirect to instructions for using CLI. Think more about how this works. Possibly allow associations and approvals without tests, but consider them “pending” until we have them)
    - View Dataset associations (benchmark owner only)
    - View MLCube associations (benchmark owner only)
    - View Benchmark results (benchmark owner only)
    - Benchmark edit
  - Benchmark submission
  - Benchmark edit
- MLCube list
  - MLCube details
  - MLCube edit
  - MLCube edit
  - MLCube submission
- Datasets list
  - Dataset details
  - Dataset edit
  - Dataset edit
  - Dataset submission
- Users List
  - User details
Signup/Login
Account management (barebones for now)

**Comment by hasan7n** [comment]
outdated
