### ISSUE TITLE
URLs of hosted files should be mutable if hashes are stored separately

### ISSUE THREAD

**Issue by msheller** [mlcommons/medperf#194]
The purpose of disallowing changing file URLs stems from the need to ensure that a given experiment's code is immutable once the experiment has begun (scientific integrity).

However, in cases where the file hash is not part of the URL (e.g. not raw github content), this immutability is unnecessary and highly inconvenient. The file-hash suffices to ensure the code has not changed.

So any file URL that has an associated hash field should be mutable to enable changing file hosts mid-experiment if needed (e.g. a file server goes offline), since the URL plays no role in ensuring the code stays the same.

Note that for github raw user content links, the hash is part of the URL, thus those URLs must remain immutable.

**Comment by hasan7n** [comment]
So it seems we also need an interface to edit entities. Something like `medperf mlcube edit kwarg=value`.
