### ISSUE TITLE
[FEATURE] Configuration Management

### ISSUE THREAD

**Issue by aristizabal95** [mlcommons/medperf#197]
**Is your feature request related to a problem? Please describe.**
The configuration is being managed through a `config.py` file, which needs to be manually edited to override the defaults.

**Describe the solution you'd like**
The configuration values should be stored in a .yaml file, which is then read and processed by the current config.py.
This config.yaml file would be copied to the `~/.medperf` on first execution.
Users should be able to change the default values via a command (`medperf config set [KWARGS]`)
Users can reset the configuration to the default settings via a command (`medperf config reset`)

**Comment by msheller** [comment]
What about having a filesystem with:

/.medperf/profiles/<name>/config.py
/.medperf/profiles/<name>/token

for user-specific stuff, and then:

/.medperf/server/<url>/datasets
/.medperf/server/<url>/mlcubes

for server-specific config (and right now, asset IDs are server-specific)?

**Comment by aristizabal95** [comment]
I'll modify Micah's proposal by placing profiles inside the respective server folder. This is because user-specific information like token is server-dependent
