### ISSUE TITLE
JSON/YAML compatibility issue in results

### ISSUE THREAD

**Issue by msheller** [mlcommons/medperf#199]
**Describe the bug**
NaNs in results.yaml files appear as ".nan", which causes JSON Decode errors when submitting them over the REST API.

**To Reproduce**
include a NaN in your results dictionary prior to writing the results .yaml file.

**Expected behavior**
Results parse correctly and can be sent to REST API

Temporary fix would be to have the medperf client include a workaround. Catch the JSONDecodeError, replace '.nan' with 'nan' and resubmit.

**Comment by aristizabal95** [comment]
This appears to be more an issue of how python encodes/decodes JSON. Inside the [json](https://docs.python.org/3/library/json.html) documentation they specify the following:

> If allow_nan is true (the default), then NaN, Infinity, and -Infinity will be encoded as such. This behavior is not JSON specification compliant, but is consistent with most JavaScript based encoders and decoders. Otherwise, it will be a [ValueError](https://docs.python.org/3/library/exceptions.html#ValueError) to encode such floats.

So we have to either:
- throw an error if one of the NaN, Infinity and -Infinity show up in any of the objects we send to the server. Not User-friendly
- Do our own encoding to JSON-Compliant equivalents. This encoding needs to be decoded by the other party that wants to process the data, and there might be situations in which the encoding collides with the actual results (Say we enconde NaN as a "nan" string, but in the future an actual result legitimately outputs "nan" as a string).

I've been doing some work on the second option. I'm currently changing the NaNs that `json` generates into Nones. This assuming that they are interchangeable. I don't know how to encode the Infinity options though. Some people suggest storing it as a huge value that will most probably get converted to infinity by any recipient of the data (e.g. `1e99999`). Any other ideas?
