### ISSUE TITLE
[FEATURE] Model Priority field for benchmark/model associations

### ISSUE THREAD

**Issue by msheller** [mlcommons/medperf#206]
Benchmark owners should be able to set the priority of models within a benchmark in the case of any time considerations (e.g. a challenge, models take 2 weeks to run, etc...). This priority should be editable by the benchmark owner.

**Comment by aristizabal95** [comment]
This priority would be part of the association. The server would ideally look at all the associations, and return the models in the order of priority. The cli would then not care about the priority, since it assumes it has already been sorted by the server

**Comment by aristizabal95** [comment]
Another option is that the client retrieves all the associations, sorts them, and retrieves all the models.
