### ISSUE TITLE
[FEATURE] Command to run all outstanding models in a benchmark

### ISSUE THREAD

**Issue by msheller** [mlcommons/medperf#207]
A data owner should be able to run a command on a given dataset and benchmark that:
1. Determines all models included in a benchmark
2. Determines the sub-list of models without current results for that dataset
3. For each model that lacks results for that dataset, in priority order (as defined by the association), creates the results
4. Results are not approved/uploaded.

**Comment by aristizabal95** [comment]
Script for running all FeTS related models has been provided [here](https://github.com/mlcommons/medperf/blob/fets-challenge/scripts/run_models.py). Although, this is only an isolated script. Should this be a medperf feature as well?

**Comment by hasan7n** [comment]
Ideally this should be worked on with https://github.com/mlcommons/medperf/issues/206
