### ISSUE TITLE
[FEATURE] Command to check (and possibly submit) all unsubmitted results for a benchmark

### ISSUE THREAD

**Issue by msheller** [mlcommons/medperf#208]
A data owner should be able to run a command that takes a given benchmark and dataset and does the following:
1. Finds all results for that dataset and benchmark pair
2. Determines the subset that haven't been approved/submitted
3. For each such result, checks for approval, and if approved, uploads the result

**Comment by aristizabal95** [comment]
The command `medperf result ls` has a field that indicates wether the results have been submitted or not. Additionally, the server rejects result submission for datasets that have not been approved yet. This means we can create this command by
1. Running `medperf result ls`.
2. Filtering the generated list by the `Submitted` and `Benchmark UID` fields.
3. Running `medperf result submit` for each result obtained previously.
4. If submission fails, then it hasn't been approved yet (Assuming we've covered other reasons why submission could normally fail like the `nan` situation).

**Comment by aristizabal95** [comment]
Script for result submission has been provided [here](https://github.com/mlcommons/medperf/blob/fets-challenge/scripts/submit_results.py)
