### ISSUE TITLE
[FEATURE] Use versioning for server and database

### ISSUE THREAD

**Issue by aristizabal95** [mlcommons/medperf#217]
**Is your feature request related to a problem? Please describe.**
Given that some breaking changes have happened (and will keep happening) with the server and the client, a lot of boilerplate code will start showing up just to cover edge cases with backwards compatibility.

**Describe the solution you'd like**
 Having a versioning methodology will allow us to support backwards compatibility in a clean manner.

**Comment by aristizabal95** [comment]
Add fields inside medperf's configuration to indicate the minimum and maximum dataset version that it supports

**Comment by aristizabal95** [comment]
The server should add the version to the API endpoints following the API versioning guidelines
https://www.django-rest-framework.org/api-guide/versioning/
https://www.django-rest-framework.org/api-guide/versioning/#urlpathversioning

**Comment by aristizabal95** [comment]
The client knows its version from pypi setup, and passes it directly to the url with something like `{url}/v{medperf.get_version()}/...`

**Comment by hasan7n** [comment]
Closing in favor of #352
