### ISSUE TITLE
[FEATURE] Read-only permissions on cube inputs (singularity)

### ISSUE THREAD

**Issue by mzenk** [mlcommons/medperf#222]
When using singularity-based cubes, we noticed that the inputs to these cubes are mounted with read-write permissions. This is unexpected for all cubes in a typical pipeline (data preparation, model and metrics) and could potentially cause reproducibility issues.

Possible solution:
In singularity, it is possible to specify mount options, which can be used to make a volume read-only. This should be the default for the input to cubes imho.

Note: This feature probably relies on a new feature of MLCube. Please raise issues as needed in that repo.

I haven't checked how docker-based cubes handle this.

**Comment by davidjurado** [comment]
Hello @mzenk 

I'm currently working on this, here is the current status of this new feature on MLCube:

[MLCube PR 267](https://github.com/mlcommons/mlcube/pull/267)

I'll let you know when it gets merge into the master branch on MLCube repo, thanks!
