### ISSUE TITLE
[BUG] MLCubes fail silently

### ISSUE THREAD

**Issue by hasan7n** [mlcommons/medperf#226]
**Describe the bug**
When running an mlcube that is supposed to fail, it seems that the failure is not being detected.

**To Reproduce**
(may not work, since sometimes medperf successfully shows errors about mlcubes failing)
What I did:
1. Submit a valid benchmark.
2. Submit a preparation cube that is compatible with the benchmark demo dataset, but its outputs are not compatible with the benchmark model.
3. Run `medperf test -b <uid> -p <uid>` using the above submitted entities.
4. The whole pipeline was executed.
5. An error is thrown only at the end

**Expected behavior**
The execution should stop once the model cube was executed.

**Additional context**
- The pipeline behaves as expected when executed individually using `mlcube` command line tool.
- I noticed that the predictions folder and the results folder are being created, but nothing is written inside them. The error at the end is due to cleanup because the results folder doesn't contain the expected file `result.yaml`.

- The cause **might** be because of `Pexpect` library returning an incorrect exit status of the mlcube execution.

**Comment by hasan7n** [comment]
The mlcube I used was running the inference task as a `subprocess`, like this:
https://github.com/mlcommons/medperf/blob/5185e4dbdd784eef27ea304424dc602c817474ff/examples/SurgMLCube/surg_prep/project/mlcube.py#L10-L14

The subprocess exited with non zero, but running `mlcube.py` exits with 0. This is captured as 0 by `docker`, then `mlcube`, then `medperf`. Not sure if this is something we can control.

**Comment by aristizabal95** [comment]
This is different to #37, because the error is caused by a subprocess inside the mlcube, and not caught by their `mlcube.py` file.

**Comment by hasan7n** [comment]
This is a problem that someone who is implementing an mlcube might fall into by mistake. I think we can safely close this after we (or the MLCube maintainers) document and present these concerns to people writing mlcubes. We should also make sure that mlcube examples in our repository are free from this behavior.
