### ISSUE TITLE
[FEATURE] Cube Checksum and redownload

### ISSUE THREAD

**Issue by aristizabal95** [mlcommons/medperf#239]
**Is your feature request related to a problem? Please describe.**
One of the biggest issues collaborators encountered during the FeTS Challenge was network issues during model retrieval. This usually caused failed image downloads that would then be either non-existent or corrupted. In these situations, we had to ask the collaborator to manually remove the failing files and try again.

**Describe the solution you'd like**
Medperf should be able to identify these situations, and retry model retrieval for a maximum number of times before reporting the issue. This is usually done with a checksum, which is something we already have implemented. This can also be implemented for additional files

**Comment by hasan7n** [comment]
Can be something like marking the cube as `invalid` on the server when retrieval fails. Such change on the server may also be associated with an automated notification to the benchmark or mlcube owner..

**Comment by aristizabal95** [comment]
We can further discuss the idea of marking a cube as invalid after a number of failing legitimate attempts from multiple users. This is not a simple thing to implement, because the action of marking a cube as invalid should not be done by other users, but by the server. Therefore, we need to implement some sort of report system where we can send failure information to the server so it can keep track and decide when to invalidate an asset.
