### ISSUE TITLE
[FEATURE] First Benchmark: Brain tumor segmentation

### ISSUE THREAD

**Issue by msheller** [mlcommons/medperf#240]
Once the FeTS Challenge completes, we need to launch our first benchmark with DKFZ/UPenn leading the committee (assuming they are still okay with this). As part of that, we should ask each participant (hospital and evaluator) if they would like to be part of this first benchmark. If so, we need to get them accounts and have them register with the primary medperf instance.

We could potentially migrate their existing information, but this has some issues regarding both compatibility if the DB changes, and process-wise (we run the risk of someone mistakenly continuing to participate by mistaking giving migration permission as being part of the challenge commitment). In other words, explicitly re-registering with the main instance helps make it clearer to participants that this is a post-challenge, opt-in activity.

**Comment by hasan7n** [comment]
In case we followed the option of migrating their existing information, this might be helpful:
https://docs.djangoproject.com/en/4.1/topics/migrations/#data-migrations

**Comment by hasan7n** [comment]
outdated
