### ISSUE TITLE
[FEATURE] Cache and check existence of compatibility test results

### ISSUE THREAD

**Issue by aristizabal95** [mlcommons/medperf#248]
**Is your feature request related to a problem? Please describe.**
Compatibility tests can take a very long time to finish depending on the use-case. This can be annoying and problematic in some cases, given that these tests are required for association requests. Even when an association compatibility test is completed, the association may be cancelled because of wrong input, or terminal timeout. Currently, if this happens, the previous test is ignored, and another test is initiated which could cause high delays and wasted computation.

**Describe the solution you'd like**
Test results should be cached in such a way that they are uniquely identified, and easily found in subsequent test executions. If a test is initiated, but results for that test already exist, then load those results and skip the test execution.

**Describe alternatives you've considered**
We have provided an autoapprove option that allows the user to avoid scenarios where the approval step might go wrong right at the end. This still won't help in cases where the test is executed twice.

**Additional context**
This is an issue that one of the FeTS contributor has been dealing with, and it has been a very annoying process of executing the compatibility test multiple times only for it to fail due to timeout in the end. The autoapprove argument was provided to avoid the same situation, but a better fix must be given.

**Comment by hasan7n** [comment]
Would caching predictions be also useful? In case the test was interrupted during the evaluation process.

**Comment by aristizabal95** [comment]
Hmm that's an interesting idea. Are you thinking on being able to resume predictions without having to redo the ones that were successful? I think it's worth thinking about this. There are a few problems I can think of:
- Medperf is problem-agnostic, so determining how to handle resuming predictions depends on the MLCube implementation.
- Because this would depend on the MLCube implementation, many side effects could arise from sharing predictions folder between executions. Example: An MLCube that creates folders in the predictions folder would fail when trying to create already-existing folders.

I propose opening a discussion on this topic to see what we come up with

**Comment by aristizabal95** [comment]
https://github.com/mlcommons/medperf/discussions/249
