### ISSUE TITLE
Docs. Main page

### ISSUE THREAD

**Issue by bekinin** [mlcommons/medperf#253]
Let's improve our main page on the docs.medperf.org and GitHub repository description.

1/ Update the medPerf description to
"MedPerf is an open-source platform for benchmarking AI models to deliver clinical efficacy."

2/ Add the GOAL just after the description
grab it from the website

OUR GOAL
Build powerful medical benchmarks securely

MedPerf is an open-source framework for benchmarking AI models to deliver clinical efficacy while prioritizing patient privacy and mitigating legal and regulatory risks. It enables federated evaluation in which AI models are securely distributed to various facilities for evaluation.

The MedPerf approach empowers healthcare organizations to assess and verify the performance of AI models in an efficient and human-supervised process without sharing any patient data across facilities during the process. It reduces the risks and costs associated with data sharing, towards maximizing medical and patient outcomes.
---

Main idea - we have the same slogan and goal across 3 places: website, docs main page, github repository page.

**Comment by bekinin** [comment]
@hasan7n  maybe you can help with this?

**Comment by hasan7n** [comment]
Complete via #255
