### ISSUE TITLE
[FEATURE] Being able to invite users to a benchmark without the need of a Dataset/MLCube

### ISSUE THREAD

**Issue by aristizabal95** [mlcommons/medperf#264]
**Is your feature request related to a problem? Please describe.**
Currently, the only way we can generate and track an interaction between benchmark owners and Datasets/MLCube owners is through associations. 

**Describe the solution you'd like**
Having the possibility to notify an user the intention to participate, and keep track of this invitation would be useful to benchmark owners.

**Describe alternatives you've considered**
For the FeTS Challenge, we achieved this through emails and by keeping track of each data owner's status through spreadsheets. Being able to provide a dashboard that accomplishes the same task would be ideal.

**Additional context**
this most probably requires server changes. To invite and track someone's participation, we need something close to a Status table, which gets updated according to the latest interaction. The client should also be able to update that status, to reflect situations like models failing or pending result submission.

**Comment by hasan7n** [comment]
oudated
