### ISSUE TITLE
[FEATURE] Multimodal Benchmark

### ISSUE THREAD

**Issue by aristizabal95** [mlcommons/medperf#266]
**Is your feature request related to a problem? Please describe.**
Current benchmarks only provide a single data preparation mlcube, which implies they only work with one specific type of data. This is sometimes not the case, since some benchmarks will require multiple dataset types, which need specific preparation implementation, and which need to be sanity checked in conjunction.

**Describe the solution you'd like**
A Benchmark should be able to contain multiple data preparator mlcubes, and they should be used according to the dataset. 

**Describe alternatives you've considered**
Keep the current design, and instead ask benchmark owners to provide a monolith data preparator, that encapsulates all the requirements to process all the types of datasets. This should be possible, but breaks the single-responsibility principle, which would be nice to keep for an mlcube to make it modular and reusable.

**Comment by hasan7n** [comment]
outdated
