### ISSUE TITLE
Better Logging in case of duplicate Dataset submission

### ISSUE THREAD

**Issue by hasan7n** [mlcommons/medperf#274]
Currently submitting the same dataset is not allowed. The reason we have this is that we want to avoid dataset collision as much as possible. A few edge cases, however, might happen while using MedPerf, and the user will not be aware that they are submitting a duplicate dataset:

1. **Datasets of the same input and output hashes:** Having different users testing the platform and using some public datasets.
2. **Datasets of different input hashes and same output hashes:** A user preparing their dataset with a different labels format and different prep cube, and unaware that the same dataset will be generated.

We should be more verbose and describe better what happened, why that is not allowed, and describe possible reasons why the user might end up with the same generated prepared data.

**Comment by aristizabal95** [comment]
This one has me a little lost. We can only tell about this duplicate submission from the server right? So what we want is to get the server to tell us where the collision happen? Or how do you envision it?

**Comment by aristizabal95** [comment]
It doesn't have to do with being verbose about the collision, but just indicating that it wasn't possible to submit because it was already submitted by someone else
