### ISSUE TITLE
Documentation for model MLCube authors

### ISSUE THREAD

**Issue by hasan7n** [mlcommons/medperf#275]
We should at some point create a walkthrough guide for model cube authors to build their MLCubes. It should contain specifics about how MedPerf expects the MLCube. An example to keep in mind:

https://github.com/mlcommons/medperf/blob/c90e7e96dbf7485f7668593f2810f4d36fd447d2/cli/medperf/config.py#L29

Cube authors should design their code (and their `mlcube.yaml` manifest) to use this path for the entry point of the additional files.

**Alternative?**
Maybe we can retrieve from the manifest file how they define their custom path names, using a function similar to this one:
https://github.com/mlcommons/medperf/blob/c90e7e96dbf7485f7668593f2810f4d36fd447d2/cli/medperf/entities/cube.py#L222-L223

**Comment by cassianomoraes** [comment]
@aristizabal95 @hasan7n I corrected the mistakes that the subsections of the three ML Cubes had in [my PR ](https://github.com/mlcommons/medperf/pull/370)
