### ISSUE TITLE
[BUG] Benchmark Owner can't fetch individual results

### ISSUE THREAD

**Issue by aristizabal95** [mlcommons/medperf#280]
**Describe the bug**
Benchmark owner should be able to access benchmark results, both from the `/benchmarks/{uid}/results` as well as `/results/{uid}`. Currently, the second option is failing, probably because of a bug with the isBenchmarkOwner check

**To Reproduce**
1. Run a server instance with benchmarks, models, datasets and results
2. Log in as the owner of a benchmark with existing results
3. Try to get results from the benchmark with `/results/{uid}` endpoint
4. See unauthorized error

**Expected behavior**
The endpoint should return individual results if the user is a benchmark owner / dataset owner related to that result

**Comment by hasan7n** [comment]
was able to reproduce but with `500 internal error`, not with an unauthorized error.
