### ISSUE TITLE
[FEATURE] Roll logs by execution instead of size

### ISSUE THREAD

**Issue by aristizabal95** [mlcommons/medperf#307]
**Is your feature request related to a problem? Please describe.**
Currently, logs are rolled depending on the size of the log file. This makes it hard to identify what logs are related to what command. Additionally, we may run into race conditions or even writing issues when two commands are executed simultaneously, since both of them will be trying to write to the same file.

**Describe the solution you'd like**
Create separate log files for each command executed. This ensures that no two commands will try to write to the same file, and also makes it easier to identify what logs are important for debugging a specific issue with a command.

**Comment by hasan7n** [comment]
closed by https://github.com/mlcommons/medperf/pull/425
