### ISSUE TITLE
[FEATURE] Homogenize Entity.all(), Entity.get()

### ISSUE THREAD

**Issue by hasan7n** [mlcommons/medperf#321]
**Is your feature request related to a problem? Please describe.**
Benchmark entities use `get` and `all` in a different way than other entities. We want to have analogous implementation across entities, to have at the end the common `Interface` object and hence minimize code maintenance in case of bugs.

**Describe the solution you'd like**
Refactor `get` and `all` in all entities.
the following will be done:
1. `all` will get all server entities, and falls back to local ones in case of communication errors.
2. `all` will have an option to use only local.
3. `get` will use `all` with `local` option when falling back to get local entities.

**Comment by aristizabal95** [comment]
I actually like more the pattern used in benchmarks regarding getting local entities. Instead of loading all local entities into memory to get the one we're interested it, we use `__get_local_dict` to retrieve it directly.
