### ISSUE TITLE
[BUG] Config options default values show as None on help message

### ISSUE THREAD

**Issue by aristizabal95** [mlcommons/medperf#334]
**Describe the bug**
Configuration options that can be passed to every command, or to the profile commands will show default values as `None`, when defaults are specified by the `config.py` file, and usually have assigned default values. This can be misleading/confusing to end-users, as they could believe everything is unset, or not know what are the actual default values without inspecting the code

**To Reproduce**
1. run `medperf --help`
2. look at config options default values

**Expected behavior**
Default values should be displayed to the user.

**Additional context**
This was known at the time of adding the configurable options. The reason this happens is because we need to recognize when an user explicitly passes an option. If using defaults, there's no way to tell which values were passed explicitly and which weren't. Although we could considered default values as unspecified option parameters, this isn't ideal for commands like `profile create` and `profile set`, where the user could want to be explicit about setting a parameter to the currently default one.

**Comment by hasan7n** [comment]
Let's also fix the following minors when working on this issue:

1) in `utils.py`
```
def storage_path(subpath: str):
    """Helper function that converts a path to storage-related path"""
    server_path = config.server.split("//")[1]
    server_path = re.sub(r"[.:]", "_", server_path)
    return os.path.join(config.storage, server_path, subpath)
```
- Better to use URL parsers instead of split "//".
- replace `/`: e.g. if someone uses a server URL like this: `https://somewhere.com/api`
or rethink a better way of assigning folder names to servers.

2) add a command `medperf profile delete -n <name>`
