### ISSUE TITLE
[FEATURE] Allow users to create a new account

### ISSUE THREAD

**Issue by hasan7n** [mlcommons/medperf#345]
**Is your feature request related to a problem? Please describe.**
Currently, users have to contact the MedPerf team to create an account.

**Describe the solution you'd like**
Implement a command to signup

**Additional context**
Their is an ongoing discussion about authentication methods ( #35 ). This issue will then depend on whether we will use Oauth or email authentication.
In either case, it is better to handle signup through a web UI, which currently we don't have.

If we plan to have this soon before the end of Q1 2023:
1) Stick with email authentication for now. Oauth can be added later.
2) Modify the server to handle email verification.
3) Have a simple signup page on https://medperf.org

**Comment by hasan7n** [comment]
Conclusion: we will not prevent users from creating accounts. We care about benchmarks, and these are going to be approved by the admin.
this issue is related to #35

**Comment by aristizabal95** [comment]
Related to #35. This will probably be covered by that same issue. Closing this one
