### ISSUE TITLE
Authentication methods

### ISSUE THREAD

**Issue by aristizabal95** [mlcommons/medperf#35]
Current authentication method depends on django sessions. We would probably want (or need) different methods for different scenarios (Web UI, 3rd-party auth). We should discuss what other solution we should implement for that (JWT? OAuth?)

**Comment by aristizabal95** [comment]
Status: these are some of the ideas that are still being proposed. A few are new
- OAuth
- OpenID
- 3rd party associations: depending on associated 3rd-party systems that already have strong authentication methods.

**Comment by aristizabal95** [comment]
Objective: Determine if we are fine for now with django, or if we should go with another solution.

**Comment by aristizabal95** [comment]
Research on email verification libraries so we don't implement it ourselves

**Comment by hasan7n** [comment]
closed by #452
