### ISSUE TITLE
Move CompatibilityTest retrieval and storage logic to a "TestReport" entity

### ISSUE THREAD

**Issue by aristizabal95** [mlcommons/medperf#371]
At the moment, we have special logic for when a benchmark execution is done with not submitted elements. We want to move this into a new entity called TestReport. This entity behaves almost the same as all entities, except that it can't interact with the server. This requres some changes to the Unit test logic.

**Comment by hasan7n** [comment]
+ fix the code pieces that deal with local mlcubes. Currently, the logic seems to be outdated
