### ISSUE TITLE
[BUG] mlcube example of ChexPert uses an image that is not on docker

### ISSUE THREAD

**Issue by hasan7n** [mlcommons/medperf#389]
- xrv-resnet uses version 0.1.0 which doesn't seem to be on dockerhub
- this was not causing errors in CLI tests because this model wasn't used:

https://github.com/mlcommons/medperf/blob/ad7dca5465f1e7cc734f21223ebb605a8caf6a45/cli/cli_xrv_demo.sh#L114

model UID should be 4 (I think)

**Comment by aristizabal95** [comment]
@hasan7n this should be fixed now. Give it a try just to make sure that's the case
