### ISSUE TITLE
Permission denied when medperf tries to delete folders generated from docker mlcubes

### ISSUE THREAD

**Issue by hasan7n** [mlcommons/medperf#414]
According to how docker is run by default, the root user owns folders generated by docker MLCubes, and hence medperf can't delete such folders.

MedPerf MLCubes generate root-owned folders only in these two steps:
- `infer` task, if the MLCube generates predictions folders inside the main output mount point (`predictions`).
- `prepare` task, if the MLCube generated prepared data folders inside the main output mount point (`data_path`).

Note: the problem doesn't happen when:
- the outputs are only files
- if the MLCube uses the singularity runner

**Why MedPerf needs to delete such folders? Two possible scenarios:**
- cleanup after a failed inference experiment. For example, if the metrics cube failed, medperf will try to cleanup the predictions folder.
- Later when we add new commands for users to delete entities (deleting a prepared dataset).

**Possible solutions?**
- We may for now catch this permission error and instruct the user to manually delete these files. We can't totally skip cleanups; clutter paths might cause problems (e.g. when listing local entities, or reruning, ...)
- There is a possibility to instruct the MLCube to run the docker image using the current user (tested):
`-Pdocker.cpu_rgs = $(id -u ${USER}):$(id -g ${USER})`
but are there any complications? (possibility of losing permissions inside the docker container, security?...)

**Comment by aristizabal95** [comment]
It is possible to pass information to the docker runner so it runs on behalf of an user (second solution you provided). The MLCube team will see if it's okay to have that by default when running Docker MLCubes, instead of defaulting to the root user

**Comment by hasan7n** [comment]
Since medperf will have sufficient permissions to rename such objects (#422 ), let's not use the solution of running docker container with the current user id as we don't know what implications this may do (e.g. user will have less permissions)

**Comment by hasan7n** [comment]
closed by #422
