### ISSUE TITLE
update tutorials MLCube links to the main repo, not forks

### ISSUE THREAD

**Issue by hasan7n** [mlcommons/medperf#418]
Also wondering: how this is usually approached? Is there a solution out there? (Now each time we want to change such links, we will end up adding another PR to use the main repo's URLs)

**Comment by VukW** [comment]
https://github.com/mlcommons/medperf/pull/517/

Commit: https://github.com/mlcommons/medperf/pull/517/commits/880e5c9307c984c4f38df0abaeb3b86d3f2e7731

I do see three possible solutions:

1. Just change the link to main's HEAD: so, you add new file in PR, during PR dev the link is wrong (it still leads to main's HEAD), but right after merge everything starts to be ok.
  - -: the links are "unstable", i.e. the same link to `mlcommons/medperf/main/path/to/file.yaml` may lead to different files once we update repo. Although I expect that files in `main` branch always be in proper state...
  - -: new links do not work properly until PR is merged
  - +: if master is always stable, links are always synced with current tutorial (that's built on master branch also) 
2. Use tags: make a `tutorial-content` tag and point to it in the link. So, link would be `https://raw.githubusercontent.com/mlcommons/medperf/tutorial-content/path/to/file.yaml` .
  - +: we can "move" the tag independently from main branch. I.e. until we do not change tutorials, tag would point on the exactly same commit not depending on new commits over main branch.
  - +: we even can tag a commit outside of `main` branch - say, use a separate branch for storing tutorial yamls.
  - -: still very hacky and weirdo. We still can move tag (or remove totally) independently of tutorial, making tutorials unconsciously broken.
3. use another hosting - say, `storage.googleapis.com` as you use it for binaries.

I've implemented (1), while believe that (3) is the best option
