### ISSUE TITLE
Polishing tutorials section in the documentation

### ISSUE THREAD

**Issue by hasan7n** [mlcommons/medperf#419]
The new section `getting started` might need a documentation expert to check if everything is worded correctly (grammar, language, ...)

Link: https://docs.medperf.org/getting_started/overview/
(All the `getting started` section)

**Comment by hasan7n** [comment]
@cassianomoraes Can you please take care of this when you have time? Thanks!

**Comment by cassianomoraes** [comment]
@hasan7n sure!

**Comment by hasan7n** [comment]
Closed by #446
