### ISSUE TITLE
Is GPU supported?

### ISSUE THREAD

**Issue by mahmoodn** [mlcommons/medperf#424]
Hi,
Does current Medperf version support GPU?

**Comment by hasan7n** [comment]
Hello @mahmoodn, thanks for submitting this issue! We will do our best to help.

MedPerf runs machine learning pipelines using [MLCubes](https://docs.medperf.org/mlcubes/mlcubes/) configured by the users. If the MLCube used in an experiment is correctly configured to use a GPU, then yes, MedPerf will allow this MLCube to use a GPU if available.

We hope that this answers your question!

**Comment by mahmoodn** [comment]
Thanks for the feedback. I will try that.
