### ISSUE TITLE
[Question] Auto-setting created datasets to OPERATION

### ISSUE THREAD

**Issue by aristizabal95** [mlcommons/medperf#44]
With the intentions of not cluttering the CLI process, I've hardcoded the dataset registration to automatically set it to `state: OPERATION`. My line of thinking is that prompting the user if he wants to set the dataset to OPERATION through the CLI feels clunky. What happens if he doesn't want to? Should we provide means for editing a registered dataset? I feel like the `state` parameter is one of those that behaves intuitively when used with an UI, but complicates flows through the CLI.

This is something that can (and most probably will) be changed in the future, but I want to check first what are the repercussions of this and how should the CLI deal with the side effects.

**Comment by hasan7n** [comment]
We will no longer have this state for datasets
