### ISSUE TITLE
[FEATURE] [BUG] Singularity Integration

### ISSUE THREAD

**Issue by laszewsk** [mlcommons/medperf#462]
This is also a bug

See also https://github.com/mlcommons/medperf/discussions/438

**Is your feature request related to a problem? Please describe.**

In some HPC machines singularity is not fully installed and is locked by a non standard and reproducable commandline specific to the machine

**Describe the solution you'd like**

We need to have a way to specify the command to create images 

* we assume that if images are placed in $SINGULARITY_CACHE the images are not rebuild but used
* we assume that when an option such as --build-images the images are build regardless if they are in the cache. E.g. they simply overwrite the image
* we assume that with a build command a shell program that takes a single def file as parameter the build can be started. So an option such as --build-command=~/bin/myspecialbuildcommand
That command would then use ~/bin/myspecialbuildcommand myimage.def when used
* we need an option to switch of fakeroot as not allowed on some HPC machines

**Describe alternatives you've considered**

did not find an alternative, maybe you can give us one

**Additional context**

Contact laszewski@gmail.com
for more details

**Comment by aristizabal95** [comment]
@anushkai We noticed you gave thumbs up. Are you having similar issues as well? I'm planning to create an email thread with the Best Practices Working Group (which are the ones in charge of singularity integration) so we can have a more in-depth discussion about this topic if possible. Do you want me to add you to that thread? If so please send me your email

**Comment by anushkai** [comment]
@aristizabal95 Yes please. My email: anb5km@virginia.edu

**Comment by hasan7n** [comment]
Closing as this was communicated to the MLCube team. Please feel free to re-open if you have any other questions.
