### ISSUE TITLE
[FEATURE] Send latest report using a Timer

### ISSUE THREAD

**Issue by aristizabal95** [mlcommons/medperf#518]
MLCubes might generate a lot of report changes in a small window of time. This could lead to an unnecessary amount of requests on our servers. We can reduce the amount of hits on our server by only sending changes after a brief period of inactivity. 

This can be done using a Timer thread.

**Comment by hasan7n** [comment]
https://github.com/mlcommons/medperf/pull/486/commits/6a7569cad886f17f35f4a90ed6ff2e92eb9ddf77
