### ISSUE TITLE
[EOF] 

### ISSUE THREAD

**Issue by Amjadzadeh** [mlcommons/medperf#610]
I hope this message finds you well. I attempted to upload images to MedPerf but encountered an issue. After running the 'MedPerf dataset prepare' command, I received an error approximately 7 hours later stating: 'There was an error while executing the cube' with the message: 'error waiting for container: unexpected EOF.' Could you please assist me in resolving this issue? Your help would be greatly appreciated.
![Image (1)](https://github.com/user-attachments/assets/2169fde9-202f-43bf-bee6-d59b9c1554ec)

**Comment by aristizabal95** [comment]
Hi,

Given this is RANO-specific, and that you probably received assitance through the communication channels we provided for this experiment, I will be closing this issue. Feel free to re-open it if the assumption above is not correct.
