### ISSUE TITLE
GCP Integration Test fails randomly

### ISSUE THREAD

**Issue by aristizabal95** [mlcommons/medperf#68]
For some reason, running the GCP integration test github action can fail at random times due to the server rejecting some action. There's little information about what is exactly the cause of it, but here are some ideas that might help find that out:
- It only happens with the remote instance of the server. Local testing is deterministic
- It can happen when populating the server through the `server.sh` script, or when executing actions through the cli. That is, this is not an isolated case for any of the scripts used in the action.
- This has a high chance of happening. For most PRs, you need to execute the action multiple times for it to finally pass.
- At the time, none of the scripts executed for integration testing displays the server response status. This could help us determine what caused the server to fail.

Demonstration of one of these cases:
https://github.com/mlcommons/medperf/runs/4921158100?check_suite_focus=true

**Comment by hasan7n** [comment]
@aristizabal95 Where are the integration tests? Could it be related to #139?

**Comment by aristizabal95** [comment]
The tests that are failing are the following
`server/seed.py` --> Tests the server endpoints and seeds the server
`cli/cli.sh` --> executes the demo workflow by talking to the server

It is not related to #139, as the error only occurs on github actions. Locally it works. So far we believe it is a problem with GCP and authentication from their side. The tests randomly get a `not authorized` response which doesn't happen locally.

**Comment by aristizabal95** [comment]
@hasan7n encountered this behavior locally, which may imply that this is not just GCP. Would be good to investigate a little more, and see if this is just network hiccups or something else hiding in the code.
