### ISSUE TITLE
Questions for Alpha Testers

### ISSUE THREAD

**Issue by msheller** [mlcommons/medperf#79]
This issue is to capture the set of questions we want to follow up with the alpha testers on as the alpha progresses.

1. Authentication sources to support (e.g. Github, Google, etc...) in beta
2. MLCube pipelines vs. single containers
3. Manual steps in the middle of preparation stages. Run as multiple stages that medperf comprehends, or run as "pauses" in the preparation cube?
4. Hosting public datasets in cloud buckets?

**Comment by aristizabal95** [comment]
The name "demo dataset" seems to be confusing

**Comment by aristizabal95** [comment]
Closing as is now going to be covered in #184
