### ISSUE TITLE
Provide input to commands through CLI arguments

### ISSUE THREAD

**Issue by aristizabal95** [mlcommons/medperf#90]
Currently all the commands that require user input use the `input()` command to retrieve such information. We should also support providing that information through CLI arguments so users can pass such information when they run the command. 

This also includes approvals, which would allow users to automate approvals for each command, allowing them just to write the initial command and let everything run on the background.

**Comment by aristizabal95** [comment]
This is now being covered by #101

**Comment by hasan7n** [comment]
Completed via #101
