### ISSUE TITLE
mlcube "tmp_submission" was executed during compatibility test

### ISSUE THREAD

**Issue by aristizabal95** [mlcommons/medperf#96]
The tmp_submission is behaving weirdly. It seems like an error was thrown when running the compatibility test. This should not be the case, as `tmp_submission` is only executed when submitting a cube. We need more info on this issue

**Comment by hasan7n** [comment]
Resolved by [this commit](https://github.com/mlcommons/medperf/pull/101/commits/45b6f275c62cb96eb1c8c946e2120fa5427f361e?diff=split&w=0#diff-3985c86e3fbba453447c3210ea55482d226a365ba4f4a24b6aa9a76d58893208).
